### ISSUE TITLE
Required changes suggestions

### ISSUE THREAD

**Issue by BANCUNGUYE66** [mnaibei/portfolio#12]
what do you think you remove some unused titles in README.md file. anyway, your project looks awesome.

**Comment by UbdaNam** [comment]
- I suggest you mention the right prerequisites in your Readme file so everyone is in ease while trying to run your project 
- please consider removing type attribute in your button tags for example: line 119 in your index html file as it is best practices of HTML semantic rules
- I suggest you to style your cards using the same class name in order to minimize duplicate code in your style sheet

**Comment by hasnatali1947** [comment]
I suggest you remove all commit code please 👍
